Parameters:
  GithubOwner:
    Type: String
    Default: qswitcher
    Description: 'Github repo owner'
  GithubRepo:
    Type: String
    Default: my-test-app
    Description: 'Github repo name'
  GithubOAuthToken:
    Type: String
    Description: 'Github personal access token'
